server:
    error:
        include-message: always
    port: 8081
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/car_service
        username: root
        password: nikhil
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: false
        show-sql: false
